name: Deploy to EC2

on:
  workflow_dispatch:
#   push:
    # branches: [ main ]  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
       npm ci
      
    - name: Build application
      run: |
        npm run build
      
    - name: Create deployment package
      run: |
        tar -czf deploy.tar.gz dist
          
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "deploy.tar.gz"
        target: "/home/ec2-user/"
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Navigate to app directory
          mkdir -p /home/ec2-user/todoapp
          cd /home/ec2-user/todoapp
          
          # Extract deployment package
          tar -xzf /home/ec2-user/deploy.tar.gz
          rm /home/ec2-user/deploy.tar.gz
          
          
          # Stop existing PM2 process if running
          pm2 stop todo-app || true
          pm2 delete todo-app || true
          
          # Start the application with PM2
          pm2 start npm --name "todo-app" -- start
          
          # Save PM2 configuration
          pm2 save
          
          # Setup PM2 to start on system boot (run once)
          sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ec2-user --hp /home/ec2-user || true