name: Deploy to EC2

on:
  workflow_dispatch:
#   push:
    # branches: [ main ]  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm install

    - name: Install client dependencies
      working-directory: ./client
      run: npm install

    - name: Build root app
      run: npm run build
      
    - name: Create deployment package
      run: |
        mkdir -p server
        cp -r dist server/
        mkdir -p server/client 
        cp -r client/dist server/client/dist
        cp package.json package-lock.json server/
        tar -czf deploy.tar.gz server
        rm -rf server

          
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "deploy.tar.gz"
        target: "/home/ec2-user/"
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          set -e

          DEPLOY_DIR="/home/ec2-user/todoapp"
          PACKAGE="/home/ec2-user/deploy.tar.gz"

          # Prepare deployment directory
          rm -rf $DEPLOY_DIR
          mkdir -p $DEPLOY_DIR
          cd $DEPLOY_DIR

          # Extract and clean up package
          tar -xzf $PACKAGE
          rm -f $PACKAGE

          # Install production dependencies
          cd server
          npm i

          # Restart the app with PM2
          pm2 stop todo-app || true
          pm2 delete todo-app || true
          pm2 start dist/server.js --name "todo-app"

          # Save PM2 process list
          pm2 save

          # Ensure PM2 auto-starts on reboot
          sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ec2-user --hp /home/ec2-user || true

