name: Terraform Deployment Pipeline

on:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  setup:
    name: Setup AWS & Terraform
    needs: checkout
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

  plan:
    name: Terraform Plan
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Apply
        run: terraform apply -auto-approve
